name: Swift Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macOS-latest  # 指定运行环境为最新版本的macOS

    steps:
    - uses: actions/checkout@v2  # 检出您的代码到运行环境
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    - name: Build and Test
      run: xcodebuild -project SSDecoder.xcodeproj -scheme SSDecoder build test | xcpretty
#   - name: Install Pods
#   run: |
#     gem install cocoapods
#     pod install
# - name: Build and Test
#   run: xcodebuild -workspace YourWorkspace.xcworkspace -scheme YourScheme build test | xcpretty

