name: Swift Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macOS-latest  # 指定运行环境为最新版本的macOS

    steps:
    - uses: actions/checkout@v2  # 检出您的代码到运行环境
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app  # 切换到特定版本的Xcode，如果需要的话
    - name: Install dependencies
      run: swift package resolve  # 安装Swift项目的依赖
    - name: Run tests
      run: swift test  # 运行单元测试
